### ISSUE TITLE
draft assemblies

### ISSUE THREAD

**Issue by hkaspersen** [rrwick/Polypolish#11]
Hello Ryan, and thank you for developing Polypolish! 
I am quite happy with the tool, and it works perfectly on long-read assemblies. I was however wondering if it is at all applicable to draft assemblies, i.e. short-read-only assemblies? Or is Pilon the only option for this available to date?

Thanks in advance!

**Comment by rrwick** [comment]
Polypolish can certainly be run on draft assemblies, but all of my development/testing was with completed long-read assemblies in mind.

Presumably your draft assembly was made with short reads and then you're polishing using the same short reads? In this case, the polishing step isn't really working with new information, so I'm not sure if Polypolish will make a draft assembly any better.

Polypolish aims to fix small-scale errors (e.g. single-bp indels), but these aren't the main problem in short-read assemblies which instead suffer from errors/fragmentation due to repeats. Pilon might help in this case (it can do local reassembly), and while I've seen it make assemblies better, I've also seen it make assemblies _worse_.

You're welcome to try Polypolish, but please view the results with a cautious eye!
