### ISSUE TITLE
When running polypolish filter, "Killed" message after 2nd Sam File gets load

### ISSUE THREAD

**Issue by schlaepferp** [rrwick/Polypolish#23]
Dear Ryan,

I installed your [Perfect-bacterial-genome-tutorial](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/tree/main)-pipeline that uses your polypolish filter and I processed the dummy example and afterwards a real example. Both ran through.

Now using it on a third example, I failed.

If I do:
`>polypolish filter --in1 alignments_1.sam --in2 alignments_2.sam --out1 filtered_1.sam --out2 filtered_2.sam`
`Starting Polypolish filter (2024-05-06 09:48:44)`
`    This runs a pre-processing filter on SAM alignments before they are used to polish. It looks at each read pair and flags alignments that do not seem to be part of a concordant pair. This can improve the accuracy Polypolish, especially near the edges of repeats.`
``
`Polypolish version: 0.6.0`
``
`Input alignments:`
`  alignments_1.sam`
`  alignments_2.sam`
``
`Output alignments:`
`  filtered_1.sam`
`  filtered_2.sam`
``
`Settings:`
`  --orientation auto`
`  --low 0.1`
`  --high 99.9`
``
``
`Loading alignments (2024-05-06 09:48:44)`
`alignments_1.sam: 10,336,620 alignments from 9,008,630 reads`
`alignments_2.sam: Killed`
`>`

Nothing else happens. Now I thought this might be because the alingnment_2.sam might be corrupt. So I reperformed the bwa command in the pipeline. It did not change the behaviour.
I then tried:

`> polypolish filter --in1 alignments_2.sam --in2 alignments_1.sam --out1 filtered_2.sam --out2 filtered_1.sam`
``
`Starting Polypolish filter (2024-05-06 09:53:18)`
`    This runs a pre-processing filter on SAM alignments before they are used to polish. It looks at each read pair and flags alignments that do not seem to be part of a concordant pair. This can improve the accuracy Polypolish, especially near the edges of repeats.`
``
`Polypolish version: 0.6.0`
``
`Input alignments:`
`  alignments_2.sam`
`  alignments_1.sam`
``
`Output alignments:`
`  filtered_2.sam`
`  filtered_1.sam`
``
`Settings:`
`  --orientation auto`
`  --low 0.1`
`  --high 99.9`
``
``
`Loading alignments (2024-05-06 09:53:18)`
`alignments_2.sam: 10,336,620 alignments from 9,008,630 reads`
`alignments_1.sam: Killed`
`>`

This means that the alignment files are not the issue. I tried to find if there is a verbosity option. but there seems not to be one. I also don't know where exactly it breaks.
I ran the entire thing on double the memobry and then it rant through. So it seems that it is a memory issue.
I suggest to check for Out of Memory Errors and then give thouse back?

Cheers,
Pascal

**Comment by rrwick** [comment]
Hi Pascal,

Yes, it does sound like a memory issue. And I also see that your alignment files seem pretty big: 9M reads probably means (depending on the read length) over 1 Gbp of sequence per read file, so that would take a decent amount of memory.

I often run things through GNU time to see how much memory they are using: `/usr/bin/time -v polypolish ...` Then you can look at the `Maximum resident set size` part of the output to see the max memory usage. Or if you're using a scheduler like SLURM, max memory might be available in the logs.

Also, if you're polishing a typical-sized bacterial genome, then your reads are probably excessively deep, and you could subsample them (e.g. with [seqtk](https://github.com/lh3/seqtk#seqtk-examples)) to lower the depth and memory usage. I would expect diminishing polishing returns over 200× depth.

Ryan
