### ISSUE TITLE
Is it appropriate to use Polypolish to perform multiple rounds of polishing

### ISSUE THREAD

**Issue by maoyibo** [rrwick/Polypolish#27]
Hi, I am trying to perform a fungal genome de novo assembly project using sequencing data from NGS+Nanopore.

I first used flye for genome assembly using nanopore data, followed by one round of polishing based on nanopore data using medaka. We are now ready to further polish the assembly using NGS data via polypolish.

Some programs, such as racon, may perform multiple rounds of polishing, while others, such as medaka, recommend only one round due to the model they are training.

So for polypolish, can we perform multiple rounds of polishing to remove as many assembly errors as possible?

Thanks in advance!

**Comment by rrwick** [comment]
You can certainly try multiple rounds, but wouldn't expect it to make much difference.

More valuable than a second round of Polypolish would be to try another polisher. I like [Pypolca](https://github.com/gbouras13/pypolca) because it has a very low rate of introducing errors, especially if you use the `--careful` parameter.

Ryan

**Comment by maoyibo** [comment]
Hi Ryan:

Your answer was very helpful.
Thank you for your work and patience.

I'll try it.

Cheers
