### ISSUE TITLE
Polypolish for metagenomes

### ISSUE THREAD

**Issue by jmtsuji** [rrwick/Polypolish#3]
Hello @rrwick ,

Thanks so much for your work on Polypolish. I am considering using Polypolish on a metagenome dataset for which I have both long (Nanopore) and short read sequencing data. The Polypolish preprint and documentation only mentions genomes as a use case, however. What are your thoughts about applying Polypolish to metagenomes?

In my case, I have assembled the Nanopore metagenome reads using Flye (in meta mode), and I then performed long read polishing using Medaka. I now hope to use Polypolish for short read polishing.

The main differences I can think of between genomes and metagenomes that could be relevant to Polypolish are:

- Uneven depth of coverage in metagenomes -- I don't think this should be an issue for Polypolish, except that some long reads probably will have insufficient coverage for error correction.
- **Potential for non-specific read mapping** -- this seems like a potential problem. If short reads maps to a related but off-target sequence in the Medaka-polished reference assembly, it could muck up the short read polishing by Polypolish (especially because Polypolish considers all mapping sites for reads).

To overcome the non-specific mapping problem, I am thinking of mapping the short reads to the Medaka-polished reference assembly with a high stringency level, e.g., only mapping short reads with a >98% match to the reference. The reference should already have low error rates after polishing with Medaka.

Do you think my proposed strategy could work, or do you recommend against using Polypolish on metagenomes? Thanks.

**Comment by rrwick** [comment]
I think your strategy makes sense, and since Polypolish was generally designed to be a 'safe' polisher (when it doubt it doesn't make a change), I do think it could be used on metagenomes.

I can, however, think of one particular case where Polypolish could introduce an error into a metagenome: when you've got a very similar sequence shared between a high-depth genome and a low-depth genome. E.g. genome A has 2000x read depth and genome B has 20x read depth, and both share some mobile genetic element. In that case, there's a risk that Polypolish could change the low-depth genome to look like the high-depth genome.

Your strategy of limiting to higher-accuracy read alignments might help (and by the way, you can implement that strategy directly in Polypolish by setting its `--max_errors` option to a lower value like 3). But the risk would still be there, e.g. if the shared sequence had 99% sequence identity. I don't think it's a big risk, so if you're not fussed about absolute maximum accuracy, I wouldn't worry about it.

But if it does matter, then I'd recommend looking for high-identity shared sequences between your genomes and somehow masking those regions in the lower-depth genomes where they occur. I.e. don't let Polypolish make any changes in those regions. I can't think of a simple way to do this, so you'd probably have to get your hands dirty with some code :smile:

Ryan

**Comment by rrwick** [comment]
Based on this, I've just added [a new bit to the FAQ](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#does-polypolish-work-on-metagenomes).

**Comment by jmtsuji** [comment]
@rrwick Thanks for the helpful response!

That is good to know about the `--max_errors` flag. In my case, because I quality-trimmed my short reads prior to read mapping, the short read length is variable. The vast majority of the reads are nearly full-length (e.g., 200 bp in my case), but a few are quite short (e.g., 80 bp). Because of the variable length, I prefer to use a % error cutoff rather than a cutoff based on an absolute number of errors. I opened my sam file in Python (using pysam) and used the "edit distance" and aligned query length to generate the percentage error value manually after read mapping by bwa-mem.

Your comment about shared sequence regions between high coverage and low coverage DNA fragments is helpful. I'll have to mull over this.

Also, in case you are curious, I tested Polypolish on my metagenome data, and it ran successfully.

Again, I appreciate your help.
