### ISSUE TITLE
Memory error while loading metagenome assembly for polishing

### ISSUE THREAD

**Issue by ckeuschn** [rrwick/Polypolish#4]
Hi, 

thanks for your work on Polypolish! 

I try to polish a gigger metagenome assembly (fasta file of 2.4Gb) from ONT reads done with MetaFlye and polished with medaka already. Currently, I get and error during the first step when the assembly is loading: 

> 
> contig_174474 (43,518 bp)
> contig_174475 (13,996 bp)
> contig_174476 (15,128 bp)
> contig_174477 (54,494 bp)
> contig_174478 (11,624 bp)
> contig_174479 (3,602 bp)
> contig_174480 (156,345 bp)
> contig_174481 (14,603 bp)
> memory allocation of 1310720 bytes failed
> /var/spool/slurmd/job626686/slurm_script : ligne 15 :  6694 Abandon                 polypolish ../polish_medaka/contigs_METAFLY_polishedMEDAKA.fasta filtered_1.sam filtered_2.sam > contigs_METAFLY_polishedMEDAKA_POLYPOLISH.fasta#

It even throws the error if I allocate the max possibe memory (700Gb) to job on the machine I work on. 
Any idea what I am missing here?
Thanks!

**Comment by rrwick** [comment]
That's definitely a much bigger assembly than I've ever tried with Polypolish, but even still, I'd think 700 GB of memory would be enough. I'm also surprised that the crash is happening in the assembly-loading step.

Can you try running it through `time` to see the memory usage? For example:
```bash
/usr/bin/time -v polypolish...
```
And then check the 'Maximum resident set size (kbytes)' line of the output. I'd just like to double check that Polypolish is genuinely using that much RAM. If it is, then perhaps we can simply conclude that Polypolish is not appropriate for such large assemblies 😬

**Comment by jmtsuji** [comment]
@ckeuschn @rrwick I had a similar memory error when running Polypolish on a metagenome assembly with a large number of contigs (~72,000 contigs!) a few weeks ago. I worked around the error by splitting the metagenome contigs file into two separate FastA files with 35,000-40,000 FastA entries per file. I then ran read mapping and Polypolish independently for the two FastA files and combined the output at the end. I suppose splitting up the FastA entries like this could result in minor differences in read mapping, but those differences should be minor, especially because the `-a` flag is being used with bwa-mem.

Back when I had this error, I remember checking the RAM use of Polypolish (just by watching `htop`), and it crashed well before reaching the memory limit of my server of 500 GB. Because of this, I think there might be some memory allocation issue inside the code itself, perhaps related to loading many separate FastA entries into RAM. I apologize that I don't have any hard records of the RAM usage by Polypolish before the crash, but I thought I should share my anecdotal experiences in case they are helpful. I agree that running `/usr/bin/time` could be a helpful next step.

**Comment by rrwick** [comment]
Thanks for the input! I'll have to play around with a big metagenome and see if I can't replicate the problem myself...

**Comment by ckeuschn** [comment]
Thanks for your resonses @rrwick, @jmtsuji. Running `/usr/bin/time` gave:

> 	Command being timed: "polypolish ../polish_medaka/contigs_METAFLY_polishedMEDAKA.fasta filtered_1.sam filtered_2.sam"
> 	User time (seconds): 18.18
> 	System time (seconds): 47.96
> 	Percent of CPU this job got: 44%
> 	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:28.87
> 	Average shared text size (kbytes): 0
> 	Average unshared data size (kbytes): 0
> 	Average stack size (kbytes): 0
> 	Average total size (kbytes): 0
> 	Maximum resident set size (kbytes): 86805908
> 	Average resident set size (kbytes): 0
> 	Major (requiring I/O) page faults: 1
> 	Minor (reclaiming a frame) page faults: 22435986
> 	Voluntary context switches: 209
> 	Involuntary context switches: 374986
> 	Swaps: 0
> 	File system inputs: 4872440
> 	File system outputs: 0
> 	Socket messages sent: 0
> 	Socket messages received: 0
> 	Signals delivered: 0
> 	Page size (bytes): 4096
> 	Exit status: 0

I had also the idea to split up the big assembly and combine after running polypolish separately on the split-files, but was not sure is this messes-up any error correction. As @jmtsuji mentioned using the -a flag should prevent major difficulties here. 

I am closing this as for now, as splitting up big assemblies seems like a reasonable workaround.
Thanks again!
