### ISSUE TITLE
Run failed after 14 hours - error not clear 

### ISSUE THREAD

**Issue by lfurn** [rrwick/Polypolish#6]
Hi Ryan, 
I ran polypolish overnight on a HPC job - slurm job script below:
#SBATCH --verbose
#SBATCH --job-nam=polypolish
#SBATCH --output=polypolish_%j.out
#SBATCH --error=polypolish_%j.err
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT

#path to bwa-mem2 executable
#./bwa-mem2-2.0pre2_x64-linux/bwa-mem2
DRAFT=foaming_project/barcode01/medaka/consensus.fasta
SHREADONE=../../../storage/nobackup/proj/tcafwi/foaming_proj/illuminia_data/Imp$
SHREADTWO=../../../storage/nobackup/proj/tcafwi/foaming_proj/illuminia_data/Imp$
#####below is quick start from polypolish
./bwa-mem2-2.0pre2_x64-linux/bwa-mem2 index ${DRAFT}
./bwa-mem2-2.0pre2_x64-linux/bwa-mem2 mem -t 16 -a ${DRAFT} ${SHREADONE} > alig$
./bwa-mem2-2.0pre2_x64-linux/bwa-mem2 mem -t 16 -a ${DRAFT} ${SHREADTWO} > alig$
Polypolish/scripts/polypolish_insert_filter.py --in1 alignments_1.sam --in2 ali$
Polypolish/target/release/polypolish ${DRAFT} filtered_1.sam filtered_2.sam > p$

Essentially the same as your example script with long paths as variables. The data is metagenomic and has been run through medaka.
The script ran for around 14hours overnight before failing with error - however the error log doesn't make it clear why it failed. polished.fasta has been made but is empty. The two alignment .sam files have data in. 
The error log is to be too large to paste in. This is the end -

[0000] 3. Calling kt_for - worker_aln
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 1066668 reads in 86.719 CPU sec, 86.7$
[0000] 2. Calling mem_process_seqs.., task: 20
[0000] 3. Calling kt_for - worker_bwt
[0000] read_chunk: 160000000, work_chunk_size: 160000200, nseq: 1066668
        [0000][ M::kt_pipeline] read 1066668 sequences (160000200 bp)...
[0000] 3. Calling kt_for - worker_aln
[0000] 10. Calling kt_for - worker_sam
        [0000][ M::mem_process_seqs] Processed 1066668 reads in 87.68

Thanks, 
Lindsey

**Comment by rrwick** [comment]
Hi Lindsey,

If your metagenome is very large, you might just be running out of resources. In particular, I'm suspicious of the `polypolish_insert_filter.py` step, as this is written in Python and is therefore less computationally efficient than the `polypolish` step (written in Rust). If your `alignments_*.sam` files look good but your `filtered_*.sam` files are empty, that would strongly suggest that the problem is with the insert-size filter step.

Since that step is optional, I'd suggest skipping it. I.e. just give the `alignments_*.sam` files to Polypolish, which will hopefully run to completion. Let me know how you go!

Ryan
